# Generated by Django 4.1.2 on 2022-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.CharField(max_length=20, null=True)),
                ('remote_user', models.CharField(max_length=50, null=True)),
                ('time_local', models.CharField(max_length=80, null=True)),
                ('request', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(null=True)),
                ('body_bytes_sent', models.IntegerField(null=True)),
                ('http_referer', models.CharField(max_length=100, null=True)),
                ('http_user_agent', models.CharField(max_length=400, null=True)),
                ('status_type', models.CharField(max_length=50, null=True)),
                ('bytes_sent', models.IntegerField(null=True)),
                ('request_time', models.FloatField(null=True)),
                ('request_path', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
