# Generated by Django 4.1.2 on 2022-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestinfo',
            table='request_info',
        ),
    ]
