# Generated by Django 4.1.2 on 2022-10-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_requestinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='time_local',
            field=models.DateTimeField(null=True),
        ),
    ]
