# Generated by Django 4.1.2 on 2022-10-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_requestinfo_time_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='request_time',
            field=models.DateTimeField(null=True),
        ),
    ]
