# Generated by Django 4.1.2 on 2022-10-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_page_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.IntegerField(default=0)),
                ('fail', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='api',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='apis', to='core.page'),
        ),
    ]
