# Generated by Django 4.1.2 on 2022-10-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_devices_deviceinfo_device_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browser',
            old_name='device',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='deviceinfo',
            old_name='device',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='os',
            old_name='device',
            new_name='request',
        ),
    ]
